version: '3.6'

networks:
  rentx_network:
    driver: bridge

services:
  app:
    build: .
    volumes:
      - .:/usr/app
    environment:
      - MONGO_URL=rentx_mongo
      - POSTGRES_URL=rentx_postgres
      - REDIS_URL=rentx_redis
    depends_on:
      - rentx_mongo
      - rentx_postgres
      - rentx_redis
    networks:
      - rentx_network
    links:
      - rentx_mongo
      - rentx_postgres
      - rentx_redis
    container_name: rentx_api
    command: yarn dev:server
    ports:
      - "3334:3334"

  rentx_mongo:
    image: bitnami/mongodb:latest
    container_name: rentx_mongo
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=no
      - MONGODB_USERNAME=${MONGO_USER}
      - MONGODB_PASSWORD=${MONGO_PASS}
      - MONGODB_DATABASE=${MONGO_DB}
    ports:
      - "27017:27017"
    volumes:
      - /tmp/mongo:/bitnami
    networks:
      - rentx_network

  rentx_redis:
    image: bitnami/redis:latest
    container_name: rentx_redis
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=no
      - REDIS_PASSWORD=${REDIS_PASS}
    ports:
      - "6379:6379"
    volumes:
      - /tmp/redis:/bitnami/redis/data
    networks:
      - rentx_network

  rentx_postgres:
    image: kartoza/postgis
    container_name: rentx_postgres
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${MONGO_PASS}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - /tmp/postgres:/data/postgres
    networks:
      - rentx_network
